name: Build and Deploy to Master
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build&Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: USE Development
        run: firebase use function-test-48x
      - name: Install Dependencies
        run: npm install
      - name: Install Functions Dependencies
        run: cd functions && npm install
      - name: Deploy to Firebase
        run: npm deploy --token=${{ secrets.FIREBASE_TOKEN }}
